#!C:\Users\OFFICE\AppData\Local\Programs\Python\Python37-32\python.exe
import mysql.connector

pythondb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="",
  database='pythondb'
)

print("Content-type: text/html\n\n")
print("Hello Sani Hyne")

con = pythondb.cursor()
query = "select * from tbl_login"
con.execute(query)

records = con.fetchall()

for row in records:
	print("log id = ", row[0], )
	print("log user = ", row[1])
	print("log date = ", row[3])
con.close()
